print("Hello Pythom i am here to learn you.")
print(2*4)
print("I started learning pyhton on 21-02-22")
print(2*4+15)
print("Python again learning start on 21-06-22")
print(2/3)
print("first commit in github in chapter no.1")
print("hello github i am here to learn you")
print("again added a commit in chaptor no.1")
